#%%
"""Build the text-only screenshot bundle used by the Road interface tour.

Keep source PNG screenshots under front-end/assets/guide/, replace them when
needed, then run this file from a Jupyter notebook or Python interactive window.
The generated JavaScript contains data URLs so Hugging Face can deploy the tour
without receiving binary image files through Git.
"""

from __future__ import annotations

import base64
from pathlib import Path


#%%
# Stable configuration: guide image ID -> local source screenshot path.
REPO_DIR = Path(__file__).resolve().parents[1]
GUIDE_ASSET_DIR = REPO_DIR / "front-end" / "assets" / "guide"
OUTPUT_PATH = REPO_DIR / "front-end" / "road-model-guide-images.js"
GUIDE_IMAGE_MANIFEST = {
    "module1_long_csv_structure": "module1-long-csv-structure.png",
    "road_model_results": "road-model-results.png",
    "road_model_dashboard": "road-model-dashboard.png",
    "leap_safe_changes_reference": "leap-safe-changes-reference.png",
    "leap_workbook_import_menu": "leap-workbook/01-import-options.png",
    "leap_workbook_import_options": "leap-workbook/02-import-workbook.png",
    "lifecycle_open_profiles": "lifecycle-profiles/15-open-lifecycle-profiles.png",
    "lifecycle_workbook_named_ranges": "lifecycle-profiles/05-workbook-named-ranges.png",
    "lifecycle_create_profile": "lifecycle-profiles/06-create-profile.png",
    "lifecycle_choose_defined_name": "lifecycle-profiles/07-choose-defined-name.png",
    "lifecycle_stock_vintage_profile": "lifecycle-profiles/08-stock-vintage-profile.png",
    "lifecycle_freight_sales_share_survival_profile": "lifecycle-profiles/09-freight-sales-share-survival-profile.png",
    "lifecycle_passenger_sales_share_survival_profile": "lifecycle-profiles/10-passenger-sales-share-survival-profile.png",
    "lifecycle_constant_excel_range": "lifecycle-profiles/12-setting-constant-profile-range.png",
    "lifecycle_mileage_constant_profile": "lifecycle-profiles/13-assign-constant-to-mileage.png",
    "lifecycle_fuel_economy_constant_profile": "lifecycle-profiles/14-assign-constant-to-fuel-economy.png",
}


#%%
def build_road_model_guide_images(
    source_directory: Path = GUIDE_ASSET_DIR,
    output_path: Path = OUTPUT_PATH,
) -> Path:
    """Encode configured local PNG assets as a browser-readable JavaScript bundle."""
    image_lines = []
    missing_paths = []

    for image_id, relative_path in GUIDE_IMAGE_MANIFEST.items():
        image_path = source_directory / relative_path
        if not image_path.is_file():
            missing_paths.append(str(image_path))
            continue
        encoded = base64.b64encode(image_path.read_bytes()).decode("ascii")
        image_lines.append(f"    {image_id!r}: 'data:image/png;base64,{encoded}',")

    if missing_paths:
        raise FileNotFoundError("Guide screenshot(s) missing:\n" + "\n".join(missing_paths))

    output_path.write_text(
        "// Generated by scripts/build_road_model_guide_images.py. Do not edit manually.\n"
        "const ROAD_MODEL_GUIDE_IMAGES = {\n"
        + "\n".join(image_lines)
        + "\n};\n",
        encoding="utf-8",
    )
    print(f"Wrote {output_path} with {len(image_lines)} encoded guide screenshots.")
    return output_path


#%%
# Toggle this block when regenerating guide screenshots after replacing local PNGs.
BUILD_GUIDE_IMAGES = True

if BUILD_GUIDE_IMAGES:
    build_road_model_guide_images()

#%%
